# Generated by Django 4.0.6 on 2022-11-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
