# Generated by Django 4.0.6 on 2022-11-12 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0004_complaint_status_com_1_complaint_status_com_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='User',
        ),
        migrations.AddField(
            model_name='complaint',
            name='Email',
            field=models.EmailField(default='default@email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='Full_name',
            field=models.CharField(default='default name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='adhaar_number',
            field=models.PositiveIntegerField(default=111111111111, validators=[django.core.validators.MaxValueValidator(999999999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone',
            field=models.CharField(default=9327434748, max_length=10),
            preserve_default=False,
        ),
    ]
