# Generated by Django 4.0.6 on 2022-11-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0005_remove_complaint_user_complaint_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
