# Generated by Django 4.0.6 on 2022-11-13 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0006_rename_email_complaint_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='adhaar_number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
