# Generated by Django 4.0.6 on 2022-11-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0007_alter_complaint_adhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
